{"name": "test_recipe_categories_reverse_relationship", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('custom_user', <SubRequest 'setup_recipe_data' for <Function test_recipe_categories_reverse_relationship>>)", "trace": "file C:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py, line 210\n      def test_recipe_categories_reverse_relationship(self, setup_recipe_data):\nfile C:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py, line 142\n      @pytest.fixture\n      def setup_recipe_data(self, custom_user):\nE       fixture 'custom_user' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _session_faker, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, capteesys, client, db, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, faker, live_server, mailoutbox, monkeypatch, other_user_data, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, setup_recipe_data, test_recipe, test_superuser, test_unit, test_unit_type, test_user, test_user_data, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\hemap\\Desktop\\cookflow-backend\\recipes\\tests\\test_model.py:142"}, "description": "Tests the reverse ManyToMany relationship from Category to Recipe.", "start": 1749832720349, "stop": 1749832720349, "uuid": "9319ff41-5deb-4ed6-91d7-7fcdbe627856", "historyId": "5dc71dce92e71f0e158f6f2312f4faf8", "testCaseId": "5dc71dce92e71f0e158f6f2312f4faf8", "fullName": "recipes.tests.test_model.TestRecipeModel#test_recipe_categories_reverse_relationship", "labels": [{"name": "tag", "value": "recipes_app"}, {"name": "tag", "value": "models"}, {"name": "tag", "value": "django_db"}, {"name": "parentSuite", "value": "recipes.tests"}, {"name": "suite", "value": "test_model"}, {"name": "subSuite", "value": "TestRecipeModel"}, {"name": "host", "value": "Pincho"}, {"name": "thread", "value": "13104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "recipes.tests.test_model"}]}